import { Inter } from "next/font/google";
import NavbarHome from "@/components/navbarHome/page";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Sistema Auditoria | Artlimp",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-BR">
      <body className={inter.className}>
        <NavbarHome />
        {children}
      </body>
    </html>
  );
}
